service: serverless-webassembly

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: pkg/wasm.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-offline

package:
  exclude:
    - target/**
